version: '3.8'

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      
  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npx tailwindcss -i ./css/app.css -o ./public/css/app.css --watch"
